class GenerateUsers {
    gender = 'mix';
    quantity = 10;
    users = [];

    maleNames = [
        'Aaron',
        'Abel',
        'Adam',
        'Adriano',
        'Afonso',
        'Alex',
        'Alexandre',
        'Álvaro',
        'André',
        'Andrei',
        'Angélico',
        'Ângelo',
        'António',
        'Armando',
        'Arthur',
        'Artur',
        'Benjamim',
        'Bernardo',
        'Brian',
        'Bruno',
        'Bryan',
        'Caio',
        'Carlos',
        'César',
        'Christian',
        'Cláudio',
        'Cristiano',
        'Daniel',
        'Danilo',
        'Dário',
        'Davi',
        'David',
        'Denis',
        'Diego',
        'Dilan',
        'Dinis',
        'Diogo',
        'Duarte',
        'Dylan',
        'Edgar',
        'Edson',
        'Eduardo',
        'Elias',
        'Emanuel',
        'Enzo',
        'Eric',
        'Erik',
        'Estêvão',
        'Ezequiel',
        'Fábio',
        'Fernando',
        'Filipe',
        'Flávio',
        'Francisco',
        'Frederico',
        'Gabriel',
        'Gaspar',
        'Gil',
        'Giovani',
        'Gonçalo',
        'Guilherme',
        'Gustavo',
        'Hélder',
        'Henrique',
        'Hugo',
        'Ian',
        'Igor',
        'Isaac',
        'Isac',
        'Isaías',
        'Isaque',
        'Ismael',
        'Iúri',
        'Ivan',
        'Ivo',
        'Jaime',
        'James',
        'Jason',
        'João',
        'Joaquim',
        'Joel',
        'Jorge',
        'José',
        'Joshua',
        'Josué',
        'Júlio',
        'Kelvin',
        'Kévim',
        'Kevin',
        'Leandro',
        'Leo',
        'Leonardo',
        'Leonel',
        'Liam',
        'Lisandro',
        'Lorenzo',
        'Lourenço',
        'Luca',
        'Lucas',
        'Luciano',
        'Luis',
        'Luís',
        'Luiz',
        'Manel',
        'Manuel',
        'Marcelo',
        'Márcio',
        'Marco',
        'Marcos',
        'Mário',
        'Martim',
        'Martin',
        'Martinho',
        'Mateus',
        'Matheus',
        'Matias',
        'Mauro',
        'Maxim',
        'Micael',
        'Miguel',
        'Moisés',
        'Muhammad',
        'Nelson',
        'Nicolas',
        'Noah',
        'Nuno',
        'Pablo',
        'Patrick',
        'Paulo',
        'Pedro',
        'Rafael',
        'Raúl',
        'Renato',
        'Ricardo',
        'Roberto',
        'Rodrigo',
        'Rogério',
        'Romeu',
        'Ruben',
        'Rúben',
        'Rui',
        'Salvador',
        'Samuel',
        'Sandro',
        'Santiago',
        'Sebastião',
        'Sérgio',
        'Simão',
        'Telmo',
        'Thiago',
        'Thomas',
        'Tiago',
        'Tomás',
        'Tomé',
        'Valentim',
        'Vasco',
        'Vicente',
        'Victor',
        'Vítor',
        'William',
        'Wilson',
        'Xavier',
        'Yuri'
    ];

    femaleNames = [
        'Abigail',
        'Adriana',
        'Alana',
        'Alexandra',
        'Alexia',
        'Aléxia',
        'Alice',
        'Alicia',
        'Alícia',
        'Aline',
        'Amália',
        'Amanda',
        'Amélia',
        'Ana',
        'Anabela',
        'Anaísa',
        'Andrea',
        'Andreia',
        'Ângela',
        'Angelina',
        'Anita',
        'Anna',
        'Antónia',
        'Ariana',
        'Ariane',
        'Áurea',
        'Aurora',
        'Bárbara',
        'Beatriz',
        'Benedita',
        'Bia',
        'Bianca',
        'Brenda',
        'Bruna',
        'Caetana',
        'Camila',
        'Carina',
        'Carla',
        'Carlota',
        'Carminho',
        'Carmo',
        'Carolina',
        'Catarina',
        'Cátia',
        'Cecília',
        'Ciara',
        'Cíntia',
        'Clara',
        'Clarisse',
        'Cláudia',
        'Constança',
        'Cristiana',
        'Cristina',
        'Dalila',
        'Dânia',
        'Daniela',
        'Daria',
        'Débora',
        'Denise',
        'Diana',
        'Doriana',
        'Eduarda',
        'Elena',
        'Eliana',
        'Eliane',
        'Elisa',
        'Ellen',
        'Ema',
        'Emília',
        'Emily',
        'Emma',
        'Erica',
        'Érica',
        'Erika',
        'Esperança',
        'Estela',
        'Ester',
        'Estrela',
        'Eva',
        'Fabiana',
        'Fátima',
        'Fernanda',
        'Filipa',
        'Flávia',
        'Flor',
        'Francisca',
        'Frederica',
        'Gabriela',
        'Giovana',
        'Giovanna',
        'Helena',
        'Iara',
        'India',
        'Inês',
        'Irene',
        'Irina',
        'Iris',
        'Íris',
        'Isa',
        'Isabel',
        'Isabela',
        'Isabella',
        'Isis',
        'Iva',
        'Jénifer',
        'Jennifer',
        'Jessica',
        'Jéssica',
        'Joana',
        'Júlia',
        'Juliana',
        'Julieta',
        'Kelly',
        'Kiara',
        'Kyara',
        'Lana',
        'Lara',
        'Larissa',
        'Laura',
        'Lea',
        'Leandra',
        'Leonor',
        'Leticia',
        'Letícia',
        'Lia',
        'Liana',
        'Liane',
        'Liliana',
        'Lisandra',
        'Lorena',
        'Luana',
        'Lúcia',
        'Luciana',
        'Luísa',
        'Luna',
        'Luz',
        'Madalena',
        'Mafalda',
        'Magda',
        'Maiara',
        'Manuela',
        'Mara',
        'Márcia',
        'Margarida',
        'Maria',
        'Mariana',
        'Marina',
        'Marisa',
        'Marta',
        'Matilde',
        'Mayara',
        'Mayra',
        'Melanie',
        'Mélanie',
        'Melissa',
        'Mia',
        'Micaela',
        'Michele',
        'Miriam',
        'Mónica',
        'Nádia',
        'Nadine',
        'Naiara',
        'Nair',
        'Natacha',
        'Nayara',
        'Neuza',
        'Nicole',
        'Nina',
        'Noa',
        'Núria',
        'Olívia',
        'Oriana',
        'Paloma',
        'Patrícia',
        'Paula',
        'Petra',
        'Pilar',
        'Priscila',
        'Rafaela',
        'Raissa',
        'Raquel',
        'Rebeca',
        'Renata',
        'Riana',
        'Rita',
        'Rosa',
        'Rute',
        'Sabrina',
        'Safira',
        'Salomé',
        'Samanta',
        'Samara',
        'Samira',
        'Sandra',
        'Sara',
        'Sarah',
        'Serena',
        'Sílvia',
        'Simone',
        'Sofia',
        'Sophia',
        'Soraia',
        'Suéli',
        'Suri',
        'Susana',
        'Taís',
        'Taísa',
        'Tamara',
        'Tânia',
        'Tatiana',
        'Telma',
        'Teresa',
        'Valentina',
        'Vanessa',
        'Vera',
        'Verónica',
        'Victoria',
        'Victória',
        'Violeta',
        'Vitória',
        'Viviane',
        'Yara',
        'Yasmin',
    ];

    surNames = [
        'Abrantes',
        'Abreu',
        'Afonso',
        'Agostinho',
        'Aguiar',
        'Aires',
        'Alberto',
        'Albuquerque',
        'Alexandre',
        'Almeida',
        'Alves',
        'Amado',
        'Amaral',
        'Amaro',
        'Amorim',
        'Andrade',
        'André',
        'Anjos',
        'António',
        'Antunes',
        'Araújo',
        'Ascensão',
        'Assunção',
        'Augusta',
        'Augusto',
        'Azevedo',
        'Baptista',
        'Barata',
        'Barbosa',
        'Barradas',
        'Barreira',
        'Barreto',
        'Barros',
        'Barroso',
        'Bastos',
        'Batista',
        'Belo',
        'Bento',
        'Bernardino',
        'Bernardo',
        'Bettencourt',
        'Borges',
        'Botelho',
        'Braga',
        'Branco',
        'Brandão',
        'Brás',
        'Braz',
        'Brito',
        'Cabral',
        'Cabrita',
        'Caeiro',
        'Caetano',
        'Calado',
        'Caldeira',
        'Camacho',
        'Câmara',
        'Campos',
        'Candeias',
        'Cardoso',
        'Carlos',
        'Carmo',
        'Carneiro',
        'Carreira',
        'Carrilho',
        'Carvalho',
        'Castanheira',
        'Castro',
        'Catarino',
        'Cavaco',
        'Cerqueira',
        'Chaves',
        'Clemente',
        'Coelho',
        'Coimbra',
        'Colaço',
        'Conceição',
        'Cordeiro',
        'Correia',
        'Costa',
        'Coutinho',
        'Couto',
        'Cristina',
        'Cruz',
        'Cunha',
        'Custódio',
        'David',
        'Delgado',
        'Dias',
        'Dinis',
        'Diogo',
        'Dionísio',
        'Domingos',
        'Domingues',
        'Dores',
        'Duarte',
        'Encarnação',
        'Esteves',
        'Faria',
        'Farinha',
        'Fátima',
        'Faustino',
        'Félix',
        'Fernandes',
        'Fernando',
        'Ferraz',
        'Ferreira',
        'Fialho',
        'Fidalgo',
        'Figueira',
        'Figueiredo',
        'Filipe',
        'Fonseca',
        'Fontes',
        'Francisco',
        'Franco',
        'Freire',
        'Freitas',
        'Furtado',
        'Galvão',
        'Gama',
        'Gameiro',
        'Garcia',
        'Gaspar',
        'Gil',
        'Glória',
        'Godinho',
        'Gomes',
        'Gonçalves',
        'Gouveia',
        'Graça',
        'Gregório',
        'Grilo',
        'Guedes',
        'Guerra',
        'Guerreiro',
        'Guimarães',
        'Henriques',
        'Horta',
        'Inácio',
        'Isabel',
        'Jacinto',
        'Jardim',
        'Jesus',
        'João',
        'Joaquim',
        'Jorge',
        'José',
        'Júnior',
        'Leal',
        'Leitão',
        'Leite',
        'Lemos',
        'Lima',
        'Lobo',
        'Lopes',
        'Loureiro',
        'Lourenço',
        'Louro',
        'Lucas',
        'Luís',
        'Luísa',
        'Lurdes',
        'Luz',
        'Macedo',
        'Machado',
        'Madeira',
        'Magalhães',
        'Maia',
        'Manuel',
        'Marcelino',
        'Maria',
        'Marinho',
        'Marques',
        'Martinho',
        'Martins',
        'Mateus',
        'Matias',
        'Matos',
        'Maurício',
        'Medeiros',
        'Meireles',
        'Melo',
        'Mendes',
        'Mendonça',
        'Meneses',
        'Mesquita',
        'Mestre',
        'Miguel',
        'Miranda',
        'Moniz',
        'Monteiro',
        'Morais',
        'Moreira',
        'Morgado',
        'Mota',
        'Moura',
        'Nascimento',
        'Neto',
        'Neves',
        'Nobre',
        'Nóbrega',
        'Nogueira',
        'Novais',
        'Nunes',
        'Oliveira',
        'Pacheco',
        'Pais',
        'Paiva',
        'Paixão',
        'Palma',
        'Parreira',
        'Patrício',
        'Paula',
        'Paulino',
        'Paulo',
        'Pedro',
        'Pedrosa',
        'Peixoto',
        'Pereira',
        'Peres',
        'Pestana',
        'Piedade',
        'Pimenta',
        'Pimentel',
        'Pina',
        'Pinheiro',
        'Pinho',
        'Pinto',
        'Pires',
        'Ponte',
        'Pontes',
        'Prazeres',
        'Proença',
        'Queirós',
        'Raimundo',
        'Ramalho',
        'Ramos',
        'Raposo',
        'Rebelo',
        'Rego',
        'Reis',
        'Resende',
        'Ribeiro',
        'Ricardo',
        'Rita',
        'Rocha',
        'Rodrigues',
        'Romão',
        'Roque',
        'Rosa',
        'Rosado',
        'Rosário',
        'Sá',
        'Salgado',
        'Salgueiro',
        'Salvador',
        'Sampaio',
        'Sanches',
        'Santana',
        'Santo',
        'Santos',
        'Saraiva',
        'Sebastião',
        'Semedo',
        'Sequeira',
        'Serra',
        'Serrano',
        'Silva',
        'Silveira',
        'Silvestre',
        'Simão',
        'Simões',
        'Soares',
        'Sobral',
        'Sousa',
        'Tavares',
        'Teixeira',
        'Teles',
        'Teresa',
        'Tomás',
        'Tomé',
        'Torres',
        'Trindade',
        'Vale',
        'Valente',
        'Varela',
        'Vasconcelos',
        'Vaz',
        'Veiga',
        'Veloso',
        'Ventura',
        'Veríssimo',
        'Viana',
        'Vicente',
        'Viegas',
        'Vieira',
        'Vilela',
        'Vitorino',
        'Xavier',
        'de Abrantes',
        'de Abreu',
        'de Afonso',
        'de Agostinho',
        'de Aguiar',
        'de Aires',
        'de Alberto',
        'de Albuquerque',
        'de Alexandre',
        'de Almeida',
        'de Alves',
        'de Amado',
        'de Amaral',
        'de Amaro',
        'de Amorim',
        'de Andrade',
        'de André',
        'de Anjos',
        'de António',
        'de Antunes',
        'de Araújo',
        'de Ascensão',
        'de Assunção',
        'de Augusta',
        'de Augusto',
        'de Azevedo',
        'de Baptista',
        'de Barata',
        'de Barbosa',
        'de Barradas',
        'de Barreira',
        'de Barreto',
        'de Barros',
        'de Barroso',
        'de Bastos',
        'de Batista',
        'de Belo',
        'de Bento',
        'de Bernardino',
        'de Bernardo',
        'de Bettencourt',
        'de Borges',
        'de Botelho',
        'de Braga',
        'de Branco',
        'de Brandão',
        'de Brás',
        'de Braz',
        'de Brito',
        'de Cabral',
        'de Cabrita',
        'de Caeiro',
        'de Caetano',
        'de Calado',
        'de Caldeira',
        'de Camacho',
        'de Câmara',
        'de Campos',
        'de Candeias',
        'de Cardoso',
        'de Carlos',
        'de Carmo',
        'de Carneiro',
        'de Carreira',
        'de Carrilho',
        'de Carvalho',
        'de Castanheira',
        'de Castro',
        'de Catarino',
        'de Cavaco',
        'de Cerqueira',
        'de Chaves',
        'de Clemente',
        'de Coelho',
        'de Coimbra',
        'de Colaço',
        'de Conceição',
        'de Cordeiro',
        'de Correia',
        'de Costa',
        'de Coutinho',
        'de Couto',
        'de Cristina',
        'de Cruz',
        'de Cunha',
        'de Custódio',
        'de David',
        'de Delgado',
        'de Dias',
        'de Dinis',
        'de Diogo',
        'de Dionísio',
        'de Domingos',
        'de Domingues',
        'de Dores',
        'de Duarte',
        'de Encarnação',
        'de Esteves',
        'de Faria',
        'de Farinha',
        'de Fátima',
        'de Faustino',
        'de Félix',
        'de Fernandes',
        'de Fernando',
        'de Ferraz',
        'de Ferreira',
        'de Fialho',
        'de Fidalgo',
        'de Figueira',
        'de Figueiredo',
        'de Filipe',
        'de Fonseca',
        'de Fontes',
        'de Francisco',
        'de Franco',
        'de Freire',
        'de Freitas',
        'de Furtado',
        'de Galvão',
        'de Gama',
        'de Gameiro',
        'de Garcia',
        'de Gaspar',
        'de Gil',
        'de Glória',
        'de Godinho',
        'de Gomes',
        'de Gonçalves',
        'de Gouveia',
        'de Graça',
        'de Gregório',
        'de Grilo',
        'de Guedes',
        'de Guerra',
        'de Guerreiro',
        'de Guimarães',
        'de Henriques',
        'de Horta',
        'de Inácio',
        'de Isabel',
        'de Jacinto',
        'de Jardim',
        'de Jesus',
        'de João',
        'de Joaquim',
        'de Jorge',
        'de José',
        'de Júnior',
        'de Leal',
        'de Leitão',
        'de Leite',
        'de Lemos',
        'de Lima',
        'de Lobo',
        'de Lopes',
        'de Loureiro',
        'de Lourenço',
        'de Louro',
        'de Lucas',
        'de Luís',
        'de Luísa',
        'de Lurdes',
        'de Luz',
        'de Macedo',
        'de Machado',
        'de Madeira',
        'de Magalhães',
        'de Maia',
        'de Manuel',
        'de Marcelino',
        'de Maria',
        'de Marinho',
        'de Marques',
        'de Martinho',
        'de Martins',
        'de Mateus',
        'de Matias',
        'de Matos',
        'de Maurício',
        'de Medeiros',
        'de Meireles',
        'de Melo',
        'de Mendes',
        'de Mendonça',
        'de Meneses',
        'de Mesquita',
        'de Mestre',
        'de Miguel',
        'de Miranda',
        'de Moniz',
        'de Monteiro',
        'de Morais',
        'de Moreira',
        'de Morgado',
        'de Mota',
        'de Moura',
        'de Nascimento',
        'de Neto',
        'de Neves',
        'de Nobre',
        'de Nóbrega',
        'de Nogueira',
        'de Novais',
        'de Nunes',
        'de Oliveira',
        'de Pacheco',
        'de Pais',
        'de Paiva',
        'de Paixão',
        'de Palma',
        'de Parreira',
        'de Patrício',
        'de Paula',
        'de Paulino',
        'de Paulo',
        'de Pedro',
        'de Pedrosa',
        'de Peixoto',
        'de Pereira',
        'de Peres',
        'de Pestana',
        'de Piedade',
        'de Pimenta',
        'de Pimentel',
        'de Pina',
        'de Pinheiro',
        'de Pinho',
        'de Pinto',
        'de Pires',
        'de Ponte',
        'de Pontes',
        'de Prazeres',
        'de Proença',
        'de Queirós',
        'de Raimundo',
        'de Ramalho',
        'de Ramos',
        'de Raposo',
        'de Rebelo',
        'de Rego',
        'de Reis',
        'de Resende',
        'de Ribeiro',
        'de Ricardo',
        'de Rita',
        'de Rocha',
        'de Rodrigues',
        'de Romão',
        'de Roque',
        'de Rosa',
        'de Rosado',
        'de Rosário',
        'de Sá',
        'de Salgado',
        'de Salgueiro',
        'de Salvador',
        'de Sampaio',
        'de Sanches',
        'de Santana',
        'de Santo',
        'de Santos',
        'de Saraiva',
        'de Sebastião',
        'de Semedo',
        'de Sequeira',
        'de Serra',
        'de Serrano',
        'de Silva',
        'de Silveira',
        'de Silvestre',
        'de Simão',
        'de Simões',
        'de Soares',
        'de Sobral',
        'de Sousa',
        'de Tavares',
        'de Teixeira',
        'de Teles',
        'de Teresa',
        'de Tomás',
        'de Tomé',
        'de Torres',
        'de Trindade',
        'de Vale',
        'de Valente',
        'de Varela',
        'de Vasconcelos',
        'de Vaz',
        'de Veiga',
        'de Veloso',
        'de Ventura',
        'de Veríssimo',
        'de Viana',
        'de Vicente',
        'de Viegas',
        'de Vieira',
        'de Vilela',
        'de Vitorino',
        'de Xavier'
    ];

    emailHosts = [
        'gmail.com',
        'hotmail.com',
        'outook.com',
        'globo.com',
        'icloud.com',
        'yahoo.com',
        'me.com',
        'live.com',
        'microsoft.com',
        '123.com',
        'fast.com',
        'hidden.com',
        'empresa_x.com',
        'empresa_y.com',
        'empresa_z.com',
        'gov.com',
        'yahoo.co.jp',
        'investing.com',
        'social.pt',
        'coupons.com',
        'autos.com',
        'computer.com',
        'zoom.com',
        'express.com',
        'ticket.com',
        'conga.com',
        'deposit.com',
        'bank.com',
        'super.com',
        'feedback.com',
        'vista.com',
        'world.com',
        'brasil.com.br',
        'portugal.pt',
        'find.com',
        'china.cn',
        'invest.com',
        'domainname.com',
        'websites.com',
        'streetfighter.com',
        'mortalkombat.com',
        'finalfantasy.com',
        'jobs.com',
        'server.com',
        'files.com',
        'games.com',
        'cinema.com',
        'local.com',
        'terra.com.br',
        'uol.com.br',
        'csgo.com',
        'couterstrike.com',
        'ryu.com',
        'ken.com',
        'chun-li.com',
        'blanka.com',
        'guile.com',
        'e-honda.com',
        'zangief.com',
        'dalsin.com',
        'balrog.com',
        'vega.com',
        'sagat.com',
        'bison.com',
        'cammy.com',
        'deejay.com',
        't-hawk.com',
        'feilong.com',
        'akuma.com',
        'guy.com',
        'cody.com',
        'hagar.com',
    ];

    constructor(gender, quantity) {
        this.gender = gender;
        this.quantity = quantity;
    };

    createEmail(fullName) {
        const emailSorted = Math.floor(Math.random() * this.emailHosts.length);
        const email = `${fullName.toLowerCase().replace(/ /g, "")}@${this.emailHosts[emailSorted]}`;
        const emailNormalized = email.normalize('NFD').replace(/[\u0300-\u036f]/g, "");
        
        return emailNormalized;
    };

    createName() {
        if (this.gender == 'any') {
            const mixedGenderNames = this.maleNames.concat(this.femaleNames);
            const firstNameSorted = Math.floor(Math.random() * mixedGenderNames.length);
            const lastNameSorted = Math.floor(Math.random() * this.surNames.length);
            const fullName = `${mixedGenderNames[firstNameSorted]} ${this.surNames[lastNameSorted]}`;
            const email = this.createEmail(fullName);

            return {
                name: fullName,
                email: email,
                password: `$2a$08$JjZyjT1k9WAAoUuf86nWG.c7Kx7/96wG1PWuuxZ7VI9HPe50AzLVW`
                //default password "123"
            };
        };

        if (this.gender == 'male') {
            const firstNameSorted = Math.floor(Math.random() * this.maleNames.length);
            const lastNameSorted = Math.floor(Math.random() * this.surNames.length);
            const fullName = `${this.maleNames[firstNameSorted]} ${this.surNames[lastNameSorted]}`;
            const email = this.createEmail(fullName);

            return {
                name: fullName,
                email: email,
                password: `$2a$08$JjZyjT1k9WAAoUuf86nWG.c7Kx7/96wG1PWuuxZ7VI9HPe50AzLVW`
                //default password "123"
            };
        }

        if (this.gender == 'female') {
            const firstNameSorted = Math.floor(Math.random() * this.femaleNames.length);
            const lastNameSorted = Math.floor(Math.random() * this.surNames.length);
            const fullName = `${this.femaleNames[firstNameSorted]} ${this.surNames[lastNameSorted]}`;
            const email = this.createEmail(fullName);

            return {
                name: fullName,
                email: email,
                password: `$2a$08$JjZyjT1k9WAAoUuf86nWG.c7Kx7/96wG1PWuuxZ7VI9HPe50AzLVW`
                //default password "123"
            };
        };
    };

    generateNames() {
        const uniqueEmailUser = new Set();

        while (this.users.length < this.quantity) {
            const user = this.createName();
            
            if (!uniqueEmailUser.has(user.email)) {
                uniqueEmailUser.add(user);
                this.users.push(user);
            };
        };

        return this.users;
    };
};

module.exports = GenerateUsers;
